CREATE TABLE PersonType
(
	PersonTypeID INT PRIMARY KEY IDENTITY(1,1),
	PersonTypeDescr VARCHAR(30),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE Person
(
	PersonID INT PRIMARY KEY IDENTITY(1,1),
	PersonTypeID INT FOREIGN KEY 
			REFERENCES PersonType (PersonTypeID),
	FirstName VARCHAR(30),
	LastName VARCHAR(30),
	DOB DATETIME NOT NULL,
	SS CHAR(11) NOT NULL,
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)

CREATE TABLE OrderType
(
	OrderTypeID INT PRIMARY KEY IDENTITY(1,1),
	OrderTypeDescr VARCHAR(30),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE Orders
(
	OrderID INT PRIMARY KEY IDENTITY(1,1),
	PersonID INT FOREIGN KEY REFERENCES Person (PersonID),
	OrderTypeID INT FOREIGN KEY REFERENCES OrderType (OrderTypeID),
	OrderQuantity INT,
	OrderDate DATETIME,
	ShipDate DATETIME,
	DeliveryDate DATETIME,
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)


--INSERT INTO tbl1 (id1, descr) VALUES(0,'test 1')
--INSERT INTO tbl2 VALUES(0,'test 2')
--SELECT @@IDENTITY
--SELECT * FROM tbl2
