CREATE TABLE PersonType
(
	PersonTypeID INT PRIMARY KEY IDENTITY(1,1),
	PersonTypeDescr VARCHAR(30),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE Person
(
	PersonID INT PRIMARY KEY IDENTITY(1,1),
	PersonTypeID INT FOREIGN KEY 
			REFERENCES PersonType (PersonTypeID),
	FirstName VARCHAR(30),
	LastName VARCHAR(30),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE AddressType
(
	AddressTypeID INT PRIMARY KEY IDENTITY(1,1),
	AddressTypeDescr VARCHAR(10),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)

CREATE TABLE "Address"
(
	AddressID INT PRIMARY KEY IDENTITY(1,1),
	AddressTypeID INT FOREIGN KEY 
			REFERENCES AddressType (AddressTypeID),
	BldgNumber VARCHAR(10),
	StName VARCHAR(30),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE VenueType
(
	VenueTypeID INT PRIMARY KEY IDENTITY(1,1),
	VenueTypeDescr VARCHAR(10),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE Venue
(
	VenueID INT PRIMARY KEY IDENTITY(1,1),
	VenueName VARCHAR(30),
	AddressID INT FOREIGN KEY REFERENCES Address (AddressID),
	VenueTypeID INT FOREIGN KEY REFERENCES VenueType (VenueTypeID),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE GearType
(
	GearTypeID INT PRIMARY KEY IDENTITY(1,1),
	GearTypeDesc VARCHAR(30),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE Gear
(
	GearID INT PRIMARY KEY IDENTITY(1,1),
	GearTypeID INT FOREIGN KEY REFERENCES GearType (GearTypeID),
	GearMake VARCHAR(30),
	GearModel VARCHAR(30),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE SongType
(
	SongTypeID INT PRIMARY KEY IDENTITY(1,1),
	SongTypeDesc VARCHAR(30),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE Song
(
	SongID INT PRIMARY KEY IDENTITY(1,1),
	SongTypeID INT FOREIGN KEY REFERENCES SongType (SongTypeID),
	SongName VARCHAR(30),
	SongArtist VARCHAR(30),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE MerchType
(
	MerchTypeID INT PRIMARY KEY IDENTITY(1,1),
	MerchTypeDesc VARCHAR(30),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE Merch
(
	MerchID INT PRIMARY KEY IDENTITY(1,1),
	MerchTypeID INT FOREIGN KEY REFERENCES MerchType (MerchTypeID),
	MerchName VARCHAR(30),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE PhoneType
(
	PhoneTypeID INT PRIMARY KEY IDENTITY(1,1),
	PhoneTypeDesc VARCHAR(30),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE Phone
(
	PhoneID INT PRIMARY KEY IDENTITY(1,1),
	PhoneTypeID INT FOREIGN KEY REFERENCES PhoneType (PhoneTypeID),
	AreaCode VARCHAR(3),
	PhoneNum VARCHAR(7),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE Album
(
	AlbumID INT PRIMARY KEY IDENTITY(1,1),
	AlbumName VARCHAR(30),
	SongID INT FOREIGN KEY REFERENCES Song (SongID),
	AlbumRelease DATETIME,
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE TourDate
(
	TourDateID INT PRIMARY KEY IDENTITY(1,1),
	ShowDate DATETIME,
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)
CREATE TABLE Setlist
(
	SetlistID INT PRIMARY KEY IDENTITY(1,1),
	TourDateID INT FOREIGN KEY REFERENCES TourDate (TourDateID),
	SongID INT FOREIGN KEY REFERENCES Song (SongID),
	DateCreated DATETIME DEFAULT GETDATE(),
	DateModified DATETIME DEFAULT GETDATE()
)




--CREATE TABLE Orders
--(
--	OrderID INT PRIMARY KEY IDENTITY(1,1),
--	PersonID INT FOREIGN KEY REFERENCES Person (PersonID),
--	OrderTypeID INT FOREIGN KEY REFERENCES OrderType (OrderTypeID),
--	OrderQuantity INT,
--	OrderDate DATETIME,
--	ShipDate DATETIME,
--	DeliveryDate DATETIME,
--	DateCreated DATETIME DEFAULT GETDATE(),
--	DateModified DATETIME DEFAULT GETDATE()
--)


--INSERT INTO tbl1 (id1, descr) VALUES(0,'test 1')
--INSERT INTO tbl2 VALUES(0,'test 2')
--SELECT @@IDENTITY
--SELECT * FROM tbl2
